# Generated by Django 5.0.7 on 2025-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgstat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('peer_type', models.CharField(default='channel', max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('image100', models.URLField(blank=True, max_length=500, null=True)),
                ('image640', models.URLField(blank=True, max_length=500, null=True)),
                ('participants_count', models.BigIntegerField(default=0)),
                ('ci_index', models.FloatField(default=0.0)),
                ('tgstat_restrictions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channel',
                'indexes': [models.Index(fields=['participants_count'], name='channel_partici_4892e6_idx'), models.Index(fields=['ci_index'], name='channel_ci_inde_dbd588_idx')],
            },
        ),
    ]
