# Generated by Django 5.0.7 on 2025-08-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_generatepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatepost',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.theme'),
        ),
    ]
