version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tgstat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  redis:
    image: redis
    ports: ["6379:6379"]

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    depends_on: [db, redis, worker, beat]
    ports: ["8000:8000"]

  worker:
    build: .
    command: celery -A tg_agregator worker -l INFO -Q celery
    env_file: .env
    depends_on: [db, redis]

  beat:
    build: .
    command: celery -A tg_agregator beat -l INFO
    env_file: .env
    depends_on: [db, redis]

volumes:
  dbdata:
